### PR TITLE
Add support for :env option

### PR DESCRIPTION
**Pull request by agilecreativity**

### CODE REVIEW

**Comment by grzm** [comment]
Looks like we've been barking up trees in the same forest :)

We've taken different approaches. I followed the pattern provided by `clojure.java.shell/sh`, where we provide the environment, whereas it looks like you're merging the provided values into the existing environment. I can see your approach being useful, but I'm unclear how I would unset environment variables, which I can also see being desirable.

**Comment by borkdude** [comment]
I think following the pattern of `clojure.java.shell/sh` would be good, since that's what people are already familiar with. To merge with the existing env you can do `:env (assoc (System/getenv) :FOO 1)` I guess?

**Comment by grzm** [comment]
That's what I was thinking with https://github.com/babashka/babashka.process/pull/10

**Comment by borkdude** [comment]
Superseded by #10.

**Pull request closed without merging**
